services:
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass passwords
    volumes:
      - /install/redis/redis_storage:/data
    networks:
      - agents-net
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - REDIS_PASSWORD=passwords
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
networks:
  agents-net:
    external: true
volumes:
  redis_storage:
    driver: local